routes/web.php
<?php

Route::get ('/', 'HomeController@index')->name ('home');
Route::get ('search', 'SearchController@index')->name ('global.search');

Route::get ('books/volumes', 'BookController@index');
Route::prefix ('books/{book}')->group (function ($book) {

  Route::get ('search', 'BookController@search')->name ('books.search');

  Route::prefix ('chapters')->group (function () {

    Route::get ('/', 'ChapterController@index')->name('chapters.index');
    Route::prefix ('{chapter}')->group (function () {

      Route::get ('/', 'ChapterController@show')->name('chapters.show');

      Route::prefix ('verses')->group (function () {

        Route::get ('/', 'VerseController@index')->name('verses.index');
        Route::prefix ('{verse_range}')->group (function () {
          Route::get ('/', 'VerseController@show')->name('verses.show');
          Route::get ('crossrefs', 'VerseController@crossrefs')->name('verses.crossrefs');
          Route::get ('similar', 'VerseController@similar')->name('verses.similar');
        });

      });

    });

  });
  Route::get ('/', 'BookController@show')->name ('books.show');

});

Route::prefix ('books/volumes/{volume?}/{ordering?}')->group (function () {
  Route::get ('/', 'BookController@index')->name ('books.index');
});

Route::get ('books', 'BookController@index');


Route::prefix ('entities')->name('entities.')->group (function () {
  Route::get ('/', 'EntityController@index')->name ('index');

  Route::prefix ('{type}')->group (function () {
    Route::prefix ('{letter}')->group (function ($letter) {
      Route::get ('/', 'EntityController@index')->name ('az');
      Route::prefix ('{entity}')->group (function () {
        Route::get ('{book}/{chapter}', 'EntityController@chapter')->name ('chapter');
        Route::get ('{book}', 'EntityController@book')->name ('book');
        Route::get ('/', 'EntityController@show')->name ('show');
      });
    });
    Route::get ('/', 'EntityController@index')->name ('type');

  });
});

Route::prefix ('frequencies')->name('frequencies.')->group (function () {
  Route::get ('/', 'FrequencyController@index')->name ('index');
  Route::prefix ('{letter}')->group (function ($letter) {
    Route::get ('/', 'FrequencyController@index')->name ('az');
    Route::get ('{frequency}/{book}/{chapter}', 'FrequencyController@chapter')->name ('chapter');
    Route::get ('{frequency}/{book}', 'FrequencyController@book')->name ('book');
    Route::get ('{frequency}', 'FrequencyController@show')->name ('show');
  });
});

Route::prefix ('topics')->name('topics.')->group (function () {
  Route::get ('/', 'TopicController@index')->name ('index');
  Route::prefix ('{letter}')->group (function ($letter) {
    Route::get ('/', 'TopicController@index')->name ('az');
    Route::get ('{topic}/{subject}', 'TopicController@show')->name ('subject');
    Route::get ('{topic}', 'TopicController@show')->name ('show');
  });
});

app/Models/Topic.php
<?php

namespace BibleNLP\Models;

use Jenssegers\Mongodb\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
use ScoutElastic\Searchable;
use BibleNLP\Search\Configurators\TopicIndexConfigurator;

/**
 * Class Topic.
 *
 * @package namespace BibleNLP\Models;
 */
class Topic extends Model implements Transformable
{
    use TransformableTrait, Searchable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'title', 'slug', 'az', 'subjects', 'refs_total'
    ];

    protected $indexConfigurator = TopicIndexConfigurator::class;

    protected $searchRules = [
        //
    ];

    // Here you can specify a mapping for a model fields.
    protected $mapping = [
        'properties' => [
            'az' => [
                'type' => 'keyword',
            ],
            'title' => [
                'type' => 'text',
            ],
            'subjects' => [
                'type' => 'text',
            ],
        ]
    ];

    public function toSearchableArray () : array {
      return [
        'az'       => $this->az,
        'title'    => $this->title,
        'subjects' => $this->title. ' ' .collect ($this->subjects)->implode (', '.$this->title.' ')
      ];
    }

    public function topic_refs () {
      return $this->hasMany (TopicRef::class);
    }

}

app/Models/TopicTable.php
<?php

namespace BibleNLP\Models;

use Jenssegers\Mongodb\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
use ScoutElastic\Searchable;
use BibleNLP\Search\Configurators\TopicTableIndexConfigurator;

/**
 * Class Topic.
 *
 * @package namespace BibleNLP\Models;
 */
class TopicTable extends Model implements Transformable
{
    use TransformableTrait, Searchable;

    protected $collection = "topic_table";

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'az',
      'root_title',
      'root_slug',
      'subject_title',
      'subject_slug',
      'root',
    ];

    protected $indexConfigurator = TopicTableIndexConfigurator::class;

    protected $searchRules = [
        //
    ];

    // Here you can specify a mapping for a model fields.
    protected $mapping = [
        'properties' => [
            'az' => [
                'type' => 'keyword',
            ],
            'root_title' => [
                'type' => 'text',
                "fields" => [
                  "analyzed" => [
                    "type" => "text",
                    "analyzer" => "partial_match_analyzer",
                  ],
                ],
            ],
            'root_slug' => [
                'type' => 'text',
                "fields" => [
                  "analyzed" => [
                    "type" => "text",
                    "analyzer" => "partial_match_analyzer",
                  ],
                ],
            ],
            'subject_title' => [
                'type' => 'text',
                "fields" => [
                  "analyzed" => [
                    "type" => "text",
                    "analyzer" => "partial_match_analyzer",
                  ],
                ],
            ],
            'subject_slug' => [
                'type' => 'text',
                "fields" => [
                  "analyzed" => [
                    "type" => "text",
                    "analyzer" => "partial_match_analyzer",
                  ],
                ],
            ],
            'root'     => [
                'type' => 'integer',
            ],
        ]
    ];

    public function toSearchableArray () : array {
      return [
        'az'            => $this->az,
        'root_title'    => $this->root_title,
        'root_slug'     => $this->root_slug,
        'subject_title' => $this->subject_title,
        'subject_slug'  => $this->subject_slug,
        'root'          => $this->root,
      ];
    }

}

app/Http/Controllers/TopicController.php
<?php

namespace BibleNLP\Http\Controllers;

use Illuminate\Http\Request;
use BibleNLP\Processors\Browsers\Topic\TopicBrowser;


use BibleNLP\Repositories\SummaryRepository;
use BibleNLP\Repositories\TopicRepository;

use BibleNLP\Criteria\WhereInCriteria;
use BibleNLP\Criteria\WhereFieldEqualsCriteria;
use BibleNLP\Criteria\GroupedTopicsCriteria;
use BibleNLP\Criteria\TopTopicsCriteria;

use BibleNLP\Models\Topic;
use Illuminate\Pagination\LengthAwarePaginator;

use \Exception;

class TopicController extends Controller
{
  private $view_subdir = 'topics.';

  public function index ( Request $request, TopicBrowser $browser, string $az = null ) {
    try {

      $this->validate_az ($az);
      return $this->view ( $this->view_subdir . 'index', array_merge ([
        'topics' => $browser->prepare ($request, $az)],
        $browser->view_vars ($request, $az))
      );

    } catch ( Exception $e ) {
      return $this->page_exception_response ($e);
    }
  }

  public function show ( Request $request, TopicBrowser $browser, $az, Topic $topic, $subject = null ) {
    try {

      $this->validate_az ($az);
      return $this->view ( $this->view_subdir . 'show', $browser->setup ($request, $az, $topic, $subject));

    } catch ( Exception $e ) {
      return $this->page_exception_response ($e);
    }
  }
}

resources/views/topics/index.blade.php
@extends ('layouts.themes.mouldify.master')

@section ('sharing')
  @include ('layouts.themes.mouldify.partials.sharing', [
    'title' => (request()->has('q') ? '&quot;' . request()->get('q') .'&quot; Search - ' : '') .' Biblical Topics '. (isset($az) ? '('.$az.')' : 'Top 100' ).' | RocketBible.com',
    'info'  => 'Search over 4900+ Biblial scriptural topics for every subject in the Bible.',
  ])
@stop

@section ('content')
  <div class="page-heading">
      <h1 class="title">Biblical Topics
        @if ( $az )
          <span class="font-weight-light"> / {{$az}} </span>
          @if ( request()->has('q') )
            <span class="font-weight-light"> / <span class="text-secondary"> {{request()->get('q')}} </span></span>
          @endif
        @else
          @if ( request()->has('q') )
            <span class="font-weight-light"> / <span class="text-secondary"> {{request()->get('q')}} </span></span>
          @else
            <span class="font-weight-light"> / <span class="text-secondary"> Top 100 </span></span>
          @endif
        @endif
      </h1>
  </div>

  <div class="row">
    <div class="col-lg-12 text-center m-b-10">
      @include ('layouts.themes.mouldify.partials.az_btns', [
        'route'     => 'topics.az',
        'selected'  => $az ?? '',
        'reset'     => 'topics.index',
      ])
    </div>
    <div class="col-lg-12 text-center mt-1">
      @include ('layouts.themes.mouldify.partials.inline_search', [
          'text'      => isset ($az) && !empty ($az) ? "Search all topics beginning with " . $az : "Search all available topics"
      ])
    </div>
  </div>


  <div class="row">

    @if ( isset($topics) && count ($topics) )


        @if ( request()->has('q') )
          <div class="col-md-12">
            <article class="gx-card mt-3">
              @foreach ( $topics AS $topic)
              <div class="col-md-12">
                @if ( $topic->root == 1)
                  <a href="{{route('topics.show', [$topic->az, str_slug($topic->root_slug)])}}">
                    <h3>{{$topic->root_title}}</h3>
                  </a>
                @else
                  <a href="{{route('topics.subject', [$topic->az, str_slug($topic->root_slug), $topic->subject_slug])}}">
                  <h3>{{fix_utf8($topic->root_title)}}<span class="font-weight-light">, {{fix_utf8($topic->subject_title)}}</span></h3>
                  </a>
                @endif
              </div>
              @endforeach
            </article>
          </div>
      @else

        @foreach ( $topics AS $topic)
        <div class="card col-md-4 p-4">
            <p class="text-uppercase letter-spacing-base mb-2 font-weight-bold">
              <a title="" href="{{route('topics.show', [$topic->az, $topic->slug])}}">
                {{str_limit($topic->title, 20)}}
              </a>
              @if ( $topic->refs_total > 0 )
                <small class="ml-2 mb-0 badge badge-light float-right">{{$topic->refs_total}}</small>
              @endif
            </p>
            @if (count ($topic->subjects))
            <table class="table table-sm ml-2 mt-2">
              <tbody>
              @if ( isset($top) )
                @foreach (collect($topic->subjects)->take(5) AS $ref)
                  <tr><td class="pl-2 font-weight-light"><a href="{{route('topics.subject', [$topic->az, $topic->slug, str_slug($ref)])}}">{{fix_utf8($ref)}}</a></td></tr>
                @endforeach
              @else
                @foreach ($topic->subjects AS $ref)
                  <tr><td class="pl-3 font-weight-light"><a href="{{route('topics.subject', [$topic->az, $topic->slug, str_slug($ref)])}}">{{fix_utf8($ref)}}</a></td></tr>
                @endforeach
              @endif
              </tbody>
            </table>
              @if ( isset($top) )
                <small class="text-right float-right">
                  <a class="gx-btn gx-btn-sm gx-btn-default" href="{{route('topics.show', [$topic->az, $topic->slug])}}">MORE</a>
                </small>
              @endif
            @endif
        </div>
        @endforeach

      @endif



    @else
      <div class="col-md-12">
        @include ('layouts.themes.mouldify.partials.empty', ['text' => 'No topics found'])
      </div>
    @endif
</div>

@if ( isset($topics) && count ($topics) && !request()->has('q') )
<div class="row text-center">
  <div class="col-md-6 m-auto text-center col-md-offset-3">
  {!! $topics->links () !!}
  </div>
</div>
@endif

@stop

resources/views/topics/show.blade.php
@extends ('layouts.themes.mouldify.master')

@section ('sharing')
  @include ('layouts.themes.mouldify.partials.sharing', [
    'title' => (request()->has('q') ?' &quot;'.request()->get('q').'&quot; Search -' : '') . $topic->title . (isset($subject) && $subject ? ' / '.fix_utf8($subject->subject) : ' - ') .' Biblical Topics | RocketBible.com',
    'info'  => 'Full breakdown of all scriptural verses categorised under '.$topic->title . (isset($subject) && $subject ? ' / '.fix_utf8($subject->subject) : '') ,
  ])
@stop

@section ('content')
  <div class="page-heading">
      <h1 class="title">
        <span class="font-weight-light">Biblical Topics / </span>
        @if ( $subject )
          <a href="{{route ('topics.show', [$az, $topic->slug])}}">
        @endif
        {{$topic->title}}
        @if ( $subject )
</a><span class="font-weight-light"> / <span class="text-secondary">{{fix_utf8($subject->subject)}}</span></span>
        @endif

      </h1>
  </div>

  <div class="row">
    <div class="col-lg-12 text-center m-b-10">
      @include ('layouts.themes.mouldify.partials.az_btns', [
        'route'     => 'topics.az',
        'selected'  => $az ?? '',
        'reset'     => 'topics.index',
      ])
    </div>
    <div class="col-lg-12 text-center mt-1">
      @include ('layouts.themes.mouldify.partials.inline_search', [
          'text'      => isset ($az) && !empty ($az) ? "Search all topics beginning with " . $az : "Search all available topics"
      ])
    </div>
  </div>

  <div style="max-height: 250px;" id="book-group-100" class="ct-perfect-fourth bible-graph topic-group-graph" data-labels='{!! json_encode($BOOKS->sortBy('order')->pluck('abbrev')->all()) !!}' data-values="{!! json_encode ([chapter_values_map($BOOKS->count(), $bible->all())]) !!}"></div>

  <div class="row mt-3">
    <div class="col-lg-8 col-sm-12">
    @if ( isset ($refs) && count ($refs) )

      @foreach ( $refs->groupBy ('subject') AS $subj => $ref_group )

          <article class="gx-card">
            <div class="gx-card-header">
              <h2>
                <a href="{{route ('topics.subject', [$az, $topic->slug, str_slug($subj)])}}">
                  {{fix_utf8($subj)}}
                </a>
              </h2>
            </div>

            <ul class="list-unstyled ml-0">
              @if ( count ($ref_group) )
                @foreach ($ref_group->sortBy('book_num')->groupBy('book_num') AS $book_num => $book_group )
                  <h3 class="font-weight-semibold clearfix">
                    {{$book_group->first()->book_title}}
                  </h3>


                  <p class="text-muted">{{$BOOKS->where('order', $book_num)->first()->summary}}</p>

                  <div class="row mb-3">
                    <div style="max-height: 150px;" id="book-group-{{str_slug($subj)}}-{{$book_num}}" class="ct-perfect-fourth topic-group-graph" data-labels='{!! json_encode(range(1, $BOOKS->where('order', $book_num)->first()->chaps)) !!}' data-values="{!! json_encode ([chapter_values_map($BOOKS->where('order', $book_num)->first()->chaps, $subject_span->get(str_slug($subj))->get($book_num)->all())]) !!}"></div>
                  </div>

                  <hr style="margin-top: 30px; margin-bottom: 30px;" />

                  <div class="row">
                  <ul class="list-unstyled ml-1 clearfix">
                    @foreach ( $book_group->sortBy('chap_num')->groupBy('chap_num') AS $chapter_group )
                      <li class="mb-2 mt-3">
                      <h3>
                        <i class="zmdi zmdi-long-arrow-right zmdi-hc-fw"></i>
                        <a class="mb-0 mr-2 badge badge-warning" href="{{route('chapters.show', [$chapter_group->first()->book_slug, $chapter_group->first()->chap_num])}}">{{$chapter_group->first()->chap_num}}</a>
                        <small class="font-weight-light text-muted">{!! fix_utf8_apos($summaries->get($book_num)->where('chap_num', $chapter_group->first()->chap_num)->first()->text['en'] ?? '') !!}</small>
                      </h3>
                        <table class="table ml-2 mt-1">
                        @foreach ($chapter_group->sortBy('verse.number') AS $ref)
                          <tr class="ml-2 mb-2">
                            <td class="center">
                              <a class="ref-verse" href="{{route ('verses.show', [$ref->book_slug, $ref->chap_num, $ref->verse->number])}}">
                                <small class="mr-2 badge badge-light">{{$ref->verse->number}}</small>
                              </a>
                            </td>
                            <td>
                              <a class="ref-verse" href="{{route ('verses.show', [$ref->book_slug, $ref->chap_num, $ref->verse->number])}}">
                                 {{$ref->ref_full_text}}
                              </a>
                            </td>
                          </tr>
                        @endforeach
                        </table>
                      </li>
                      <hr style="margin-top: 30px; margin-bottom: 30px;" />
                    @endforeach
                  </ul>
                  </div>



                @endforeach
              @else
                @include ('layouts.themes.mouldify.partials.empty', ['text' => 'No references found'])
              @endif
            </ul>

          </article>

      @endforeach
      </div>

      <div class="col-md-4 col-sm-12">
        @include ('layouts.themes.mouldify.partials.grouped_topic_list', ['topics'=>$topic->topic_refs->sortBy('title')->groupBy ('title')])
      </div>
      <div class="row text-center">
        <div class="col-md-6 col-md-offset-3 text-center m-auto">
        {!! $refs->links () !!}
        </div>
      </div>


    @else
      @include ('layouts.themes.mouldify.partials.empty', ['text' => 'No topic references found'])
    @endif
  </div>




@stop