routes/web.php
<?php

Route::get ('/', 'HomeController@index')->name ('home');
Route::get ('search', 'SearchController@index')->name ('global.search');

Route::get ('books/volumes', 'BookController@index');
Route::prefix ('books/{book}')->group (function ($book) {

  Route::get ('search', 'BookController@search')->name ('books.search');

  Route::prefix ('chapters')->group (function () {

    Route::get ('/', 'ChapterController@index')->name('chapters.index');
    Route::prefix ('{chapter}')->group (function () {

      Route::get ('/', 'ChapterController@show')->name('chapters.show');

      Route::prefix ('verses')->group (function () {

        Route::get ('/', 'VerseController@index')->name('verses.index');
        Route::prefix ('{verse_range}')->group (function () {
          Route::get ('/', 'VerseController@show')->name('verses.show');
          Route::get ('crossrefs', 'VerseController@crossrefs')->name('verses.crossrefs');
          Route::get ('similar', 'VerseController@similar')->name('verses.similar');
        });

      });

    });

  });
  Route::get ('/', 'BookController@show')->name ('books.show');

});

Route::prefix ('books/volumes/{volume?}/{ordering?}')->group (function () {
  Route::get ('/', 'BookController@index')->name ('books.index');
});

Route::get ('books', 'BookController@index');


Route::prefix ('entities')->name('entities.')->group (function () {
  Route::get ('/', 'EntityController@index')->name ('index');

  Route::prefix ('{type}')->group (function () {
    Route::prefix ('{letter}')->group (function ($letter) {
      Route::get ('/', 'EntityController@index')->name ('az');
      Route::prefix ('{entity}')->group (function () {
        Route::get ('{book}/{chapter}', 'EntityController@chapter')->name ('chapter');
        Route::get ('{book}', 'EntityController@book')->name ('book');
        Route::get ('/', 'EntityController@show')->name ('show');
      });
    });
    Route::get ('/', 'EntityController@index')->name ('type');

  });
});

Route::prefix ('frequencies')->name('frequencies.')->group (function () {
  Route::get ('/', 'FrequencyController@index')->name ('index');
  Route::prefix ('{letter}')->group (function ($letter) {
    Route::get ('/', 'FrequencyController@index')->name ('az');
    Route::get ('{frequency}/{book}/{chapter}', 'FrequencyController@chapter')->name ('chapter');
    Route::get ('{frequency}/{book}', 'FrequencyController@book')->name ('book');
    Route::get ('{frequency}', 'FrequencyController@show')->name ('show');
  });
});

Route::prefix ('topics')->name('topics.')->group (function () {
  Route::get ('/', 'TopicController@index')->name ('index');
  Route::prefix ('{letter}')->group (function ($letter) {
    Route::get ('/', 'TopicController@index')->name ('az');
    Route::get ('{topic}/{subject}', 'TopicController@show')->name ('subject');
    Route::get ('{topic}', 'TopicController@show')->name ('show');
  });
});

app/Models/Frequency.php
<?php

namespace BibleNLP\Models;

use Jenssegers\Mongodb\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
use ScoutElastic\Searchable;
use BibleNLP\Search\Configurators\FrequencyIndexConfigurator;

/**
 * Class Frequency.
 *
 * @package namespace BibleNLP\Models;
 */
class Frequency extends Model implements Transformable
{
    use TransformableTrait, Searchable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'container_type',
      'container_id',
      'word',
      'total',
      'az',
      'book_num',
      'book_title',
      'book_slug',
      'chap_num',
    ];

    protected $indexConfigurator = FrequencyIndexConfigurator::class;

    protected $searchRules = [
        //
    ];

    // Here you can specify a mapping for a model fields.
    protected $mapping = [
        'properties' => [
          'az' => [
              'type' => 'keyword',
              "fields" => [
                "analyzed" => [
                  "type" => "text",
                  "analyzer" => "partial_match_analyzer",
                ],
              ],
          ],
          'word' => [
              'type' => 'text',
              "fields" => [
                "analyzed" => [
                  "type" => "text",
                  "analyzer" => "partial_match_analyzer",
                ],
              ],
          ],
          'slug' => [
              'type' => 'text',
              "fields" => [
                "analyzed" => [
                  "type" => "text",
                  "analyzer" => "partial_match_analyzer",
                ],
              ],
          ],
        ]
    ];

    public function toSearchableArray () : array {
      return [
        'az'        => $this->az,
        'word'      => $this->word,
        'slug'      => str_slug($this->word),
      ];
    }

    public function shouldBeSearchable () {
      return $this->container_type == 'GLOBAL' ? true : false;
    }

    public function chapter () {
      return $this->belongsTo (Chapter::class, 'container_id');
    }

    public function instances () {
        return $this->hasMany (Instance::class)->where ('reference_type', Verse::class);
    }

}

app/Http/Controllers/FrequencyController.php
<?php

namespace BibleNLP\Http\Controllers;

use Illuminate\Http\Request;

use BibleNLP\Processors\Browsers\Frequency\FrequencyBrowser;
use BibleNLP\Processors\Browsers\Frequency\BookFrequencyBrowser;
use BibleNLP\Processors\Browsers\Frequency\ChapterFrequencyBrowser;

use BibleNLP\Models\Book;
use BibleNLP\Models\Frequency;

use \Exception;

class FrequencyController extends Controller
{
  private $view_subdir = 'frequencies.';

  public function index ( Request $request, FrequencyBrowser $browser, string $az = null ) {
    try {

      $this->validate_az ($az);

      return $this->view ( $this->view_subdir . 'index', array_merge ([
          'frequencies' => $browser->prepare ($request, $az),
        ], $browser->view_vars ($request, $az))
      );

    } catch ( Exception $e ) {
      return $this->page_exception_response ($e);
    }
  }

  public function show ( Request $request, FrequencyBrowser $browser, string $az, Frequency $frequency ) {
    try {

      $this->validate_az ($az);
      return $this->view ( $this->view_subdir . 'show', $browser->setup ($request, $az, $frequency));

    } catch ( Exception $e ) {
      return $this->page_exception_response ($e);
    }
  }

  public function book ( Request $request, BookFrequencyBrowser $browser, string $az, Frequency $frequency, Book $book ) {
    try {

      $this->validate_az ($az);
      return $this->view ( $this->view_subdir . 'book', $browser->setup ($request, $az, $frequency, $book));

    } catch ( Exception $e ) {
      return $this->page_exception_response ($e);
    }
  }

  public function chapter ( Request $request, ChapterFrequencyBrowser $browser, string $az, Frequency $frequency, Book $book, int $chap_num ) {
    try {

      $this->validate_az ($az);
      $this->validate_chapter ($book, $chap_num);

      return $this->view ( $this->view_subdir . 'chapter', $browser->setup ($request, $az, $frequency, $book, $chap_num));

    } catch ( Exception $e ) {
      return $this->page_exception_response ($e);
    }
  }

}

resources/views/frequencies/book.blade.php
@extends ('layouts.themes.mouldify.master')

@section ('sharing')
  @include ('layouts.themes.mouldify.partials.sharing', [
    'title' => 'Occurrences of &quot;'.title_case ($frequency->word).'&quot; found in ' .$book->title. '('.$mentions->sum('total').') - Biblical Word Frequencies | RocketBible.com',
    'info'  => '',
  ])
<meta property="og:type" content="books.genre">
<meta property="books:canonical_name" content="{{$book->title}}">
<meta property="books:book" content="{{htmlentities($book->summary)}}">
@stop

@section ('content')
  <div class="page-heading">
      <h1 class="title">
        Biblical Word Frequencies
          <span class="font-weight-light"> / <span class="text-secondary">{{$frequency->word}}</span> / Found In </span>
          {{$book->title}}
          <span class="mr-2 badge badge-secondary float-right">{{$mentions->sum('total')}}</span>
      </h1>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="gx-card">
        <p class="text-muted lead">{{$book->summary}}</p>

        <div style="max-height: 150px;" id="book-group-{{$book->order}}" class="ct-perfect-fourth book-group-graph" data-labels="{{json_encode(range(1, $book->chaps))}}" data-values="{!! json_encode ([chapter_values_map($book->chaps, $chap_count->all())]) !!}"></div>

        <hr style="margin-top: 30px; margin-bottom: 30px;" />

        <ul class="list-unstyled ml-1 clearfix">
        @foreach ( $chapters AS $chapter )
          @if ($mentions->whereIn ('container_id', $chapter->verses->pluck('id'))->count() > 0)
          <li class="mb-2 mt-2">
          <h3 class="">
            <i class="zmdi zmdi-long-arrow-right zmdi-hc-fw"></i>
            <a class="mb-0 mr-2 badge badge-warning" href="{{route('frequencies.chapter', [$az, $frequency->word, $book->slug, $chapter->number])}}">{{$chapter->number}}</a>
            <small class="font-weight-light text-muted">{!! fix_utf8_apos($chapter->summaries->first()->text['en'] ?? '') !!}</small>
          </h3>


            <div class="row mt-0 mb-3">
              <div class="col-md-7 pl-2">
                @if (count ($mentions) )
                  <table class="table table-sm col-md-6 col-md-offset-3 ml-3">
                    <thead>
                      <tr>
                        <th class="text-center">Verse</th>
                        <th class="text-center">Count </th>
                        <th class="text-center">Context </th>
                      </tr>
                    </thead>
                    <tbody>
                    @foreach ($chapter->verses->sortBy('number') AS $verse)
                      @if ( $mentions->contains ('container_id', $verse->id) )
                      <tr>
                        <td class="text-center">
                        {{$verse->number}}
                        </td>
                        <td class="text-center">
                          <span class="badge badge-light">{{$mentions->where('container_id', $verse->id)->first()->total}}</span>
                        </td>
                        <td>
                          <a class="ref-verse" href="{{route ('verses.show', [$verse->book_slug, $verse->chap_num, $verse->number])}}">
                             {!! searchword( $verse->text['en'], [$frequency->word], 'verse-100') !!}
                          </a>
                        </td>
                      </tr>
                      @endif
                    @endforeach
                    </tbody>
                  </table>

                @else
                  @include ('layouts.themes.mouldify.partials.empty', ['text' => 'No results found.'])
                @endif
              </div>
              <div class="col-md-5 pt-3">
                <canvas id="chapter-radar-{{$chapter->number}}" class="chapter-radar-graph mt-3 m-auto" data-labels="{{json_encode(range(1, $chapter->verses->count()))}}"
                  data-values="{!! json_encode (chapter_values_map($chapter->verses->count(),  $chapter->verses->filter(function ($value, $key) use ($mentions) {
                      return $mentions->contains ('container_id', $value->id);
                  })->mapWithKeys(function ($item) use ($mentions) {
                    return [$item->number => $mentions->where('container_id', $item->id)->first()->total];
                  })->sortKeys()->all())) !!}">
                </canvas>
              </div>
            </div>
          </li>
          <hr style="margin-top: 30px; margin-bottom: 30px;" />
          @endif
        @endforeach
      </ul>
      @include ('layouts.themes.mouldify.partials.frequency_disclaimer')
    </div>
  </div>
</div>


@stop

resources/views/frequencies/chapter.blade.php
@extends ('layouts.themes.mouldify.master')

@section ('sharing')
  @include ('layouts.themes.mouldify.partials.sharing', [
    'title' => 'Occurrences of &quot;'.title_case ($frequency->word).'&quot; found in '.$chapter->canonical. ' ('.$mentions->sum('total').') - Biblical Word Frequencies | RocketBible.com',
    'info'  => '',
  ])
<meta property="og:type" content="books.genre">
<meta property="books:canonical_name" content="{{$book->title}}">
<meta property="books:book" content="{{htmlentities($book->summary)}}">
@stop

@section ('content')
  <div class="page-heading">
      <h1 class="title">
        Biblical Word Frequencies
          <span class="font-weight-light"> / <span class="text-secondary">{{$frequency->word}}</span> / Found In </span>
          {{$chapter->canonical}}
          <span class="mr-2 badge badge-secondary float-right">{{$mentions->sum('total')}}</span>
      </h1>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="gx-card">
          <p class="text-muted lead">{{$book->summary}}</p>
          <p class="font-weight-light ml-3"><i class="zmdi zmdi-long-arrow-right zmdi-hc-fw"></i>
            <a class="mb-0 mr-2 badge badge-warning" href="{{route('chapters.show', [$book->slug, $chapter->number])}}">{{$chapter->number}}</a>
             {!! fix_utf8_apos($chapter->summaries->first()->text['en'] ?? '') !!}</p>
          <hr style="margin-top: 30px; margin-bottom: 30px;" />

          <div style="max-height: 150px;" id="book-group-{{$book->order}}" class="ct-perfect-fourth book-group-graph ml-0" data-labels="{{json_encode(range(1, $chapter->verses->count()))}}" data-values="{!! json_encode ([chapter_values_map($chapter->verses->count(), $verse_count->all())]) !!}"></div>

            <div class="row mt-0 mb-3">
              <div class="col-md-7 pl-2">
                @if (count ($mentions) )
                  <table class="table table-sm col-md-6 col-md-offset-3 ml-3">
                    <thead>
                      <tr>
                        <th class="text-center">Verse</th>
                        <th class="text-center">Count </th>
                        <th class="text-center">Context </th>
                      </tr>
                    </thead>
                    <tbody>
                    @foreach ($chapter->verses->sortBy('number') AS $verse)
                      @if ( $mentions->contains ('container_id', $verse->id) )
                      <tr>
                        <td class="text-center">
                        {{$verse->number}}
                        </td>
                        <td class="text-center">
                          <span class="badge badge-light">{{$mentions->where('container_id', $verse->id)->first()->total}}</span>
                        </td>
                        <td>
                          <a class="ref-verse" href="{{route ('verses.show', [$verse->book_slug, $verse->chap_num, $verse->number])}}">
                             {!! searchword( $verse->text['en'], [$frequency->word], 'verse-100') !!}
                          </a>
                        </td>
                      </tr>
                      @endif
                    @endforeach
                    </tbody>
                  </table>
                @else
                  @include ('layouts.themes.mouldify.partials.empty', ['text' => 'No results found.'])
                @endif
              </div>
              <div class="col-md-5" style="padding-top: 4rem;">
                <canvas id="chapter-radar-{{$chapter->number}}" class="chapter-radar-graph mt-3 m-auto" data-labels="{{json_encode(range(1, $chapter->verses->count()))}}"
                  data-values="{!! json_encode (chapter_values_map($chapter->verses->count(),  $verse_count->all())) !!}">
                </canvas>
              </div>
            </div>
          @include ('layouts.themes.mouldify.partials.frequency_disclaimer')
    </div>
  </div>
</div>


@stop

resources/views/frequencies/index.blade.php
@extends ('layouts.themes.mouldify.master')

@section ('sharing')
  @include ('layouts.themes.mouldify.partials.sharing', [
    'title' => 'Biblical Word Frequencies - '.(request()->has('q') ? '&quot;'.request()->get('q').'&quot; Search -' : '') . (isset($az) ? '('.$az.') - ' : 'Top 100').'  | RocketBible.com',
    'info'  => '',
  ])
@stop

@push ('head')
  <style>
  .badge-ext {
    width: 35px !important;
    padding: 5px 5px !important;
  }
  </style>
@endpush

@section ('content')
  <div class="page-heading">
      <h1 class="title">
        Biblical Word Frequencies
        @if ( isset($az) && !empty ($az) )
          <span class="font-weight-light"> / {{$az}} </span>
          @if ( request()->has('q') )
            <span class="font-weight-light"> / <span class="text-secondary"> {{request()->get('q')}} </span></span>
          @endif
        @else
          @if ( request()->has('q') )
            <span class="font-weight-light"> / <span class="text-secondary"> {{request()->get('q')}} </span></span>
          @else
            <span class="font-weight-light"> / <span class="text-secondary"> Top 100 </span></span>
          @endif

        @endif
      </h1>
  </div>

  <div class="row">
    <div class="col-lg-12 text-center m-b-10">
      @include ('layouts.themes.mouldify.partials.az_btns', [
        'route'     => 'frequencies.az',
        'selected'  => $az ?? '',
        'reset'     => 'frequencies.index',
      ])
    </div>
    <div class="col-lg-12 text-center mt-1">
      @include ('layouts.themes.mouldify.partials.inline_search', [
          'text'      => isset ($az) && !empty ($az) ? "Search all word occurrences beginning with " . $az : "Search all words in the Bible"
      ])
    </div>
  </div>


  <div class="row">
    <div class="col-lg-12">
      <div class="gx-card">
        <div class="" role="group">
          @if ( isset($frequencies) && count ($frequencies) )
            @foreach ($frequencies AS $freq )
                <a class="gx-btn gx-btn-default col-md-2" href="{{route ('frequencies.show', [$freq->az, $freq->word])}}">
                  {{title_case($freq->word)}}
                  <small class="mb-0 badge badge-light badge-ext float-right">{{$freq->total}}</small>
                </a>
            @endforeach
          @else
            <div class="col-md-12">
              @include ('layouts.themes.mouldify.partials.empty', ['text' => 'No word occurrences found'])
            </div>
          @endif

        </div>
        @include ('layouts.themes.mouldify.partials.frequency_disclaimer')
    </div>
  </div>
</div>

@if ( isset($frequencies) && count ($frequencies) && !request()->has('q') )
<div class="row text-center">
  <div class="col-md-6 col-md-offset-3 m-auto">
    {!! $frequencies->links () !!}
  </div>
</div>
@endif

@stop

resources/views/frequencies/show.blade.php
@extends ('layouts.themes.mouldify.master')

@section ('sharing')
  @include ('layouts.themes.mouldify.partials.sharing', [
    'title' => '&quot;'.title_case ($frequency->word).'&quot; - Biblical Word Frequencies | RocketBible.com',
    'info'  => '',
  ])
@stop

@section ('content')

  <div class="page-heading">
    <div class="row d-block d-md-none mb-2">
      <div class="col-sm-12 col-xs-12 text-right float-right">
        <span class="mr-4 badge badge-secondary">{{$frequency->total}}</span>
      </div>
    </div>
    <div class="row clearfix" style="clear:both;">
      <h1 class="title col-xs-12 col-sm-12 pl-3 pr-2 text-center">
        Biblical Word Frequencies
        <span class="font-weight-light"> / <span class="text-secondary">{{$frequency->word}}</span> </span>
          <span class="mr-2 badge badge-secondary float-right d-none d-sm-block">{{$frequency->total}}</span>
      </h1>
    </div>
  </div>

  <div class="row mb-3">
    <div style="max-height: 250px;" id="book-group-100" class="ct-perfect-fourth bible-graph book-group-graph" data-labels='{!! json_encode($BOOKS->sortBy('order')->pluck('abbrev')->all()) !!}' data-values="{!! json_encode ([chapter_values_map($BOOKS->count(), $bible->all())]) !!}"></div>
  </div>


  <div class="row">
    <div class="col-lg-12">
      <div class="gx-card">
        @if ( isset($chapters) && count ($chapters) )
          @foreach ($chapters->groupBy('book_num') AS $book_num => $book_group)
            <h3 class="font-weight-semibold clearfix mt-3">
              <a href="{{route ('frequencies.book', [$az, $book_group->first()->word, $book_group->first()->book_slug])}}">
                {{$book_group->first()->book_title}}
              </a>

              <small class="mr-2 badge badge-secondary ml-2">{{$book_group->sum('total')}}</small>
            </h3>

            <p class="text-muted">{{$BOOKS->where('order', $book_num)->first()->summary}}</p>

            <div class="row">
              <div style="max-height: 150px;" id="book-group-{{$book_num}}" class="ct-perfect-fourth book-group-graph" data-labels="{{json_encode(range(1, $BOOKS->where('order', $book_num)->first()->chaps))}}" data-values="{!! json_encode ([chapter_values_map($BOOKS->where('order', $book_num)->first()->chaps, $book_group->sortBy ('chap_num')->pluck('total', 'chap_num')->all())]) !!}"></div>
            </div>

            <div class="row mt-0 mb-3">

              <div class="col-md-4 pl-2">
                @if (count ($book_group) )
                  <table class="table table-sm col-md-6 col-md-offset-3 ml-3">
                    <thead>
                      <tr>
                        <th class="text-center">Chapter</th>
                        <th class="text-center">Count </th>
                      </tr>
                    </thead>
                    <tbody>
                    @foreach ($book_group->sortBy ('chap_num') AS $chap_freq)
                    <tr>
                      <td width="30%" class="text-center">
                        <a class="ml-2 mb-0 badge badge-warning" href="{{route ('frequencies.chapter', [$az, $chap_freq->word, $chap_freq->book_slug, $chap_freq->chap_num])}}">{{$chap_freq->chap_num}}</a>
                      </td>
                      <td width="30%" class="text-center">
                        <span class="badge badge-light">{{$chap_freq->total}}</span>
                      </td>
                    </tr>
                    @endforeach
                    </tbody>
                  </table>
                @else
                  @include ('layouts.themes.mouldify.partials.empty', ['text' => 'No results found.'])
                @endif
              </div>

              <div class="col-md-4 text-center pt-3 pl-3">
                <div id="chapter-gauge-{{$book_num}}" style="margin-left: 5rem;" class="mt-3 float-right chapter-gauge-graph m-auto" data-total="{{$book_group->sum('total')}}" data-values="{!! json_encode ($book_group->sortBy ('chap_num')->pluck('total', 'chap_num')->values()->all()) !!}"></div>
              </div>
              <div class="col-md-4 text-center pt-3">
                <canvas id="chapter-radar-{{$book_num}}" class="chapter-radar-graph mt-3 m-auto" data-labels="{{json_encode(range(1, $BOOKS->where('order', $book_num)->first()->chaps))}}" data-values="{!! json_encode (chapter_values_map($BOOKS->where('order', $book_num)->first()->chaps, $book_group->sortBy ('chap_num')->pluck('total', 'chap_num')->all())) !!}"></canvas>
              </div>

            </div>
            <hr style="margin-top: 30px; margin-bottom: 30px;" />
          @endforeach

          <div class="row mt-0 mb-3 text-center">
            <div class="col-md-3 col-md-offset-1 m-auto text-center">
              {!! $chapters->links() !!}
            </div>
          </div>
          @include ('layouts.themes.mouldify.partials.frequency_disclaimer')

        @else
          @include ('layouts.themes.mouldify.partials.empty', ['text' => 'No results found in any book.'])
        @endif

    </div>
  </div>
</div>


@stop