routes/web.php
<?php

Route::get ('/', 'HomeController@index')->name ('home');
Route::get ('search', 'SearchController@index')->name ('global.search');

Route::get ('books/volumes', 'BookController@index');
Route::prefix ('books/{book}')->group (function ($book) {

  Route::get ('search', 'BookController@search')->name ('books.search');

  Route::prefix ('chapters')->group (function () {

    Route::get ('/', 'ChapterController@index')->name('chapters.index');
    Route::prefix ('{chapter}')->group (function () {

      Route::get ('/', 'ChapterController@show')->name('chapters.show');

      Route::prefix ('verses')->group (function () {

        Route::get ('/', 'VerseController@index')->name('verses.index');
        Route::prefix ('{verse_range}')->group (function () {
          Route::get ('/', 'VerseController@show')->name('verses.show');
          Route::get ('crossrefs', 'VerseController@crossrefs')->name('verses.crossrefs');
          Route::get ('similar', 'VerseController@similar')->name('verses.similar');
        });

      });

    });

  });
  Route::get ('/', 'BookController@show')->name ('books.show');

});

Route::prefix ('books/volumes/{volume?}/{ordering?}')->group (function () {
  Route::get ('/', 'BookController@index')->name ('books.index');
});

Route::get ('books', 'BookController@index');


Route::prefix ('entities')->name('entities.')->group (function () {
  Route::get ('/', 'EntityController@index')->name ('index');

  Route::prefix ('{type}')->group (function () {
    Route::prefix ('{letter}')->group (function ($letter) {
      Route::get ('/', 'EntityController@index')->name ('az');
      Route::prefix ('{entity}')->group (function () {
        Route::get ('{book}/{chapter}', 'EntityController@chapter')->name ('chapter');
        Route::get ('{book}', 'EntityController@book')->name ('book');
        Route::get ('/', 'EntityController@show')->name ('show');
      });
    });
    Route::get ('/', 'EntityController@index')->name ('type');

  });
});

Route::prefix ('frequencies')->name('frequencies.')->group (function () {
  Route::get ('/', 'FrequencyController@index')->name ('index');
  Route::prefix ('{letter}')->group (function ($letter) {
    Route::get ('/', 'FrequencyController@index')->name ('az');
    Route::get ('{frequency}/{book}/{chapter}', 'FrequencyController@chapter')->name ('chapter');
    Route::get ('{frequency}/{book}', 'FrequencyController@book')->name ('book');
    Route::get ('{frequency}', 'FrequencyController@show')->name ('show');
  });
});

Route::prefix ('topics')->name('topics.')->group (function () {
  Route::get ('/', 'TopicController@index')->name ('index');
  Route::prefix ('{letter}')->group (function ($letter) {
    Route::get ('/', 'TopicController@index')->name ('az');
    Route::get ('{topic}/{subject}', 'TopicController@show')->name ('subject');
    Route::get ('{topic}', 'TopicController@show')->name ('show');
  });
});

app/Models/Entity.php
<?php

namespace BibleNLP\Models;

use Jenssegers\Mongodb\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
use ScoutElastic\Searchable;
use BibleNLP\Search\Configurators\EntityIndexConfigurator;

/**
 * Class Entity.
 *
 * @package namespace BibleNLP\Models;
 */
class Entity extends Model implements Transformable
{
    use TransformableTrait, Searchable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'name',
      'slug',
      'type',
      'az',
      'refs_total',
    ];

    protected $indexConfigurator = EntityIndexConfigurator::class;

    protected $searchRules = [
        //
    ];

    // Here you can specify a mapping for a model fields.
    protected $mapping = [
        'properties' => [
          'az' => [
              'type' => 'keyword',
              "fields" => [
                "analyzed" => [
                  "type" => "text",
                  "analyzer" => "partial_match_analyzer",
                ],
              ],
          ],
          'type' => [
              'type' => 'keyword',
              "fields" => [
                "analyzed" => [
                  "type" => "text",
                  "analyzer" => "partial_match_analyzer",
                ],
              ],
          ],
          'name' => [
              'type' => 'text',
              "fields" => [
                "analyzed" => [
                  "type" => "text",
                  "analyzer" => "partial_match_analyzer",
                ],
              ],
          ],
          'slug' => [
              'type' => 'text',
              "fields" => [
                "analyzed" => [
                  "type" => "text",
                  "analyzer" => "partial_match_analyzer",
                ],
              ],
          ],
        ]
    ];

    public function toSearchableArray () : array {
      return [
        'az'    => $this->az,
        'type'  => $this->type,
        'name'  => $this->name,
        'slug'  => str_slug($this->name),
      ];
    }

    public function entity_refs () {
      return $this->hasMany ( EntityRef::class );
    }

}

app/Http/Controllers/EntityController.php
<?php

namespace BibleNLP\Http\Controllers;

use Illuminate\Http\Request;

use BibleNLP\Processors\Browsers\Entity\EntityBrowser;
use BibleNLP\Processors\Browsers\Entity\BookEntityBrowser;
use BibleNLP\Processors\Browsers\Entity\ChapterEntityBrowser;

use BibleNLP\Models\Book;
use \Exception;

class EntityController extends Controller
{

  private $view_subdir = 'entities.';

  public function index ( Request $request, EntityBrowser $browser, string $type = 'all', string $az = null ) {
    try {

      $this->validate_entity_type ($type);
      $this->validate_az ($az);

      return $this->view ( $this->view_subdir . 'index', array_merge ([
        'entities'      => $browser->prepare ($request, $type, $az),
      ], $browser->view_vars ($request, $type, $az)));

    } catch ( Exception $e ) {
      return $this->page_exception_response ($e);
    }
  }

  public function show ( Request $request, EntityBrowser $browser, string $type, string $az, string $entity_slug ) {
    try {

      $this->validate_entity_type ($type);
      $this->validate_az ($az);

      return $this->view ( $this->view_subdir . 'show', $browser->setup ($request, $type, $az, $entity_slug));

    } catch ( Exception $e ) {
      return $this->page_exception_response ($e);
    }
  }

  public function book ( Request $request, BookEntityBrowser $browser, string $type, string $az, string $entity_slug, Book $book ) {
    try {

      $this->validate_entity_type ($type);
      $this->validate_az ($az);

      return $this->view ( $this->view_subdir . 'book', $browser->setup ($request, $type, $az, $entity_slug, $book));

    } catch ( Exception $e ) {
      return $this->page_exception_response ($e);
    }
  }

  public function chapter ( Request $request, ChapterEntityBrowser $browser, string $type, string $az, string $entity_slug, Book $book, int $chap_num ) {
    try {

      $this->validate_entity_type ($type);
      $this->validate_az ($az);
      $this->validate_chapter ($book, $chap_num);

      return $this->view ( $this->view_subdir . 'chapter', $browser->setup ($request, $type, $az, $entity_slug, $book, $chap_num));

    } catch ( Exception $e ) {
      return $this->page_exception_response ($e);
    }
  }


}

resources/views/entities/book.blade.php
@extends ('layouts.themes.mouldify.master')

@section ('sharing')
  @include ('layouts.themes.mouldify.partials.sharing', [
    'title' => 'Occurrences of '.title_case ($entity->name) .(isset($type) ? ' ('.entity_label($type).')' : '').' found in .'.$book->title.' ('.$mentions->count().') - Named Biblical Entities | RocketBible.com',
    'info'  => '',
  ])
<meta property="og:type" content="books.genre">
<meta property="books:canonical_name" content="{{$book->title}}">
<meta property="books:book" content="{{htmlentities($book->summary)}}">
@stop


@section ('content')
  <div class="page-heading">
    <div class="row d-block d-md-none mb-2">
      <div class="col-sm-12 text-right">
        <span class="mr-4 badge badge-secondary">{{$mentions->count()}}</span>
      </div>
    </div>
    <div class="row clearfix">
      <h1 class="title col-xs-12 pl-1 pr-2">
        Named Entities
          <span class="font-weight-light"> / {{entity_label($type)}} / <span class="text-secondary">{{title_case($entity->name)}}</span> / found in </span> {{$book->title}}
          <span class="mr-2 badge badge-secondary float-right d-none d-sm-block">{{$mentions->count()}}</span>
      </h1>
    </div>
  </div>



  <div class="row">
    <div class="col-lg-12">
      <div class="gx-card">

        <p class="text-muted lead">{{$book->summary}}</p>

        <div style="max-height: 150px;" id="book-group-{{$book->order}}" class="ct-perfect-fourth book-group-graph" data-labels="{{json_encode(range(1, $book->chaps))}}" data-values="{!! json_encode ([chapter_values_map($book->chaps, $chap_count->all())]) !!}"></div>

        <hr style="margin-top: 30px; margin-bottom: 30px;" />

        <ul class="list-unstyled ml-1 clearfix">
        @foreach ( $chapters->sortBy('number') AS $chapter )
          @if ($mentions->whereIn ('reference_id', $chapter->verses->pluck('id'))->count() > 0)
          <li class="mb-2 mt-2">
          <h3><i class="zmdi zmdi-long-arrow-right zmdi-hc-fw"></i>
            <a class="mb-0 mr-2 badge badge-warning" href="{{route('entities.chapter', [$type, $az, $entity->slug, $book->slug, $chapter->number])}}">{{$chapter->number}}</a>
            <small class="font-weight-light text-muted">{!! fix_utf8_apos($chapter->summaries->first()->text['en'] ?? '') !!}</small>
          </h3>

            <div class="row mt-0 mb-3">
              <div class="col-md-7 pl-2">
                @if (count ($mentions) )
                  <table class="table table-sm col-md-6 col-md-offset-3 ml-3">
                    <thead>
                      <tr>
                        <th class="text-center">Verse</th>
                        <th class="text-center">Count </th>
                        <th class="text-center">Context </th>
                      </tr>
                    </thead>
                    <tbody>
                    @foreach ($chapter->verses->sortBy('number') AS $verse)
                      @if ( $mentions->contains ('reference_id', $verse->id) )
                      <tr>
                        <td class="text-center">
                        {{$verse->number}}
                        </td>
                        <td class="text-center">
                          <span class="badge badge-light">{{$mentions->where('reference_id', $verse->id)->first()->mentions}}</span>
                        </td>
                        <td>
                          <a class="ref-verse" href="{{route ('verses.show', [$verse->book_slug, $verse->chap_num, $verse->number])}}">
                             {!! searchword( $verse->text['en'], [$entity->name], 'verse-100') !!}
                          </a>
                        </td>
                      </tr>
                      @endif
                    @endforeach
                    </tbody>
                  </table>
                @else
                  @include ('layouts.themes.mouldify.partials.empty', ['text' => 'No results found.'])
                @endif
              </div>
              <div class="col-md-5 pt-3">

                <canvas id="chapter-radar-{{$chapter->number}}" class="chapter-radar-graph mt-3 m-auto" data-labels="{{json_encode(range(1, $chapter->verses->count()))}}"
                  data-values="{!! json_encode (chapter_values_map($chapter->verses->count(),  $chapter->verses->filter(function ($value, $key) use ($mentions) {
                      return $mentions->contains ('reference_id', $value->id);
                  })->mapWithKeys(function ($item) use ($mentions) {
                    return [$item->number => $mentions->where('reference_id', $item->id)->first()->mentions];
                  })->sortKeys()->all())) !!}">
                </canvas>

              </div>
            </div>
            <hr style="margin-top: 30px; margin-bottom: 30px;" />
          </li>

          @endif
        @endforeach
      </ul>
      @include ('layouts.themes.mouldify.partials.entity_disclaimer')
    </div>
  </div>
</div>


@stop

resources/views/entities/chapter.blade.php
@extends ('layouts.themes.mouldify.master')

@section ('sharing')
  @include ('layouts.themes.mouldify.partials.sharing', [
    'title' => 'Occurrences of '.title_case ($entity->name) .(isset($type) ? ' ('.entity_label($type).')' : '').' found in .'.$chapter->canonical.' ('.$mentions->count().') - Named Biblical Entities | RocketBible.com',
    'info'  => '',
  ])
<meta property="og:type" content="books.genre">
<meta property="books:canonical_name" content="{{$book->title}}">
<meta property="books:book" content="{{htmlentities($book->summary)}}">
@stop

@section ('content')

  <div class="page-heading">
    <div class="row d-block d-md-none mb-2">
      <div class="col-sm-12 col-xs-12 text-right float-right">
        <span class="mr-4 badge badge-secondary">{{$mentions->count()}}</span>
      </div>
    </div>
    <div class="row clearfix" style="clear:both;">
      <h1 class="title col-xs-12 col-sm-12 pl-3 pr-2 text-center">
        Named Entities
          <span class="font-weight-light"> / {{entity_label($type)}} / <span class="text-secondary">{{title_case($entity->name)}}</span> / </span> {{$chapter->canonical}}
          <span class="mr-2 badge badge-secondary float-right d-none d-sm-block">{{$mentions->count()}}</span>
      </h1>
    </div>
  </div>


  <div class="row">
    <div class="col-lg-12">
      <div class="gx-card">
        <p class="text-muted lead">{{$book->summary}}</p>
        <p class="font-weight-light ml-3"><i class="zmdi zmdi-long-arrow-right zmdi-hc-fw"></i>
          <a class="mb-0 mr-2 badge badge-warning" href="{{route('chapters.show', [$book->slug, $chapter->number])}}">{{$chapter->number}}</a>
           {!! fix_utf8_apos($chapter->summaries->first()->text['en'] ?? '') !!}</p>
        <hr style="margin-top: 30px; margin-bottom: 30px;" />

        <div style="max-height: 150px;" id="book-group-{{$book->order}}" class="ct-perfect-fourth book-group-graph ml-0" data-labels="{{json_encode(range(1, $chapter->verses->count()))}}" data-values="{!! json_encode ([chapter_values_map($chapter->verses->count(), $verse_count->all())]) !!}"></div>


            <div class="row mt-0 mb-3">
              <div class="col-md-7 pl-2">
                @if (count ($mentions) )
                  <table class="table table-sm col-md-6 col-md-offset-3 ml-3">
                    <thead>
                      <tr>
                        <th class="text-center">Verse</th>
                        <th class="text-center">Count </th>
                        <th class="text-center">Context </th>
                      </tr>
                    </thead>
                    <tbody>
                    @foreach ($chapter->verses->sortBy('number') AS $verse)
                      @if ( $mentions->contains ('reference_id', $verse->id) )
                      <tr>
                        <td class="text-center">
                        {{$verse->number}}
                        </td>
                        <td class="text-center">
                          <span class="badge badge-light">{{$mentions->where('reference_id', $verse->id)->first()->mentions}}</span>
                        </td>
                        <td>
                          <a class="ref-verse" href="{{route ('verses.show', [$verse->book_slug, $verse->chap_num, $verse->number])}}">
                             {!! searchword( $verse->text['en'], [$entity->name], 'verse-100') !!}
                          </a>
                        </td>
                      </tr>
                      @endif
                    @endforeach
                    </tbody>
                  </table>
                @else
                  @include ('layouts.themes.mouldify.partials.empty', ['text' => 'No results found.'])
                @endif
              </div>
              <div class="col-md-5" style="padding-top: 4rem;">

                <canvas id="chapter-radar-{{$chapter->number}}" class="chapter-radar-graph mt-3 m-auto" data-labels="{{json_encode(range(1, $chapter->verses->count()))}}"
                  data-values="{!! json_encode (chapter_values_map($chapter->verses->count(),  $verse_count->all())) !!}">
                </canvas>

              </div>
            </div>

        @include ('layouts.themes.mouldify.partials.entity_disclaimer')
    </div>
  </div>
</div>


@stop

resources/views/entities/index.blade.php
@extends ('layouts.themes.mouldify.master')

@section ('sharing')
  @include ('layouts.themes.mouldify.partials.sharing', [
    'title' => (request()->has('q') ? '&quot;'.request()->get('q').'&quot; Search -' : '') .(isset($type) ? entity_label($type) : '') . (isset($az) ? ' ('.$az.')' : ' - Top 100 - ').' Named Biblical Entities | RocketBible.com',
    'info'  => '',
  ])
@stop

@push ('head')
  <style>
  .badge-ext {
    width: 35px !important;
    padding: 5px 5px !important;
  }
  </style>
@endpush

@section ('content')
  <div class="page-heading">
      <h1 class="title">Entities
        @if ( isset ($type) && $type != 'all' )
          <span class="font-weight-light"> / {{entity_label($type)}} </span>
          @if ( $az )
            <span class="font-weight-light"> / {{$az}}</span>
            @if ( request()->has('q') )
              <span class="font-weight-light"> / <span class="text-secondary"> {{request()->get('q')}} </span></span>
            @endif

          @else
            @if ( request()->has('q') )
              <span class="font-weight-light"> / <span class="text-secondary"> {{request()->get('q')}} </span></span>
            @else
              <span class="font-weight-light">   / </span>
            <span class="font-weight-light text-secondary"> Top 100 </span>
            @endif
          @endif
        @else
          @if ( request()->has('q') )
            <span class="font-weight-light"> / <span class="text-secondary"> {{request()->get('q')}} </span></span>
          @else
            <span class="font-weight-light"> / <span class="text-secondary"> Top 100 </span></span>
          @endif
        @endif
      </h1>
  </div>

  <div class="row">
    <div class="col-lg-12 text-center m-b-10">
      @include ('layouts.themes.mouldify.partials.az_btns_entities', [
        'route'     => 'entities.az',
        'selected'  => $az ?? '',
        'type'      => $type ?? 'person',
        'reset'     => isset($type) ? route ('entities.type', $type) : route('entities.index'),
      ])
    </div>
    <div class="col-lg-12 text-center mt-1">
      @include ('layouts.themes.mouldify.partials.inline_search', [
          'text'      => isset ($az) && !empty ($az) ? "Search all entities beginning with " . $az : "Search all available entities"
      ])
    </div>
  </div>


  <div class="row">
    <div class="col-lg-12">
          <div class="gx-card gx-card-full-height">
            <div class="card-header">
              @include ('layouts.themes.mouldify.partials.entity_tabs', ['type'=>$type, 'az' => $az])
            </div>

            <div class="mt-2" role="group">
              @if ( isset($entities) && count ($entities) )
                @foreach ($entities AS $entity )
                    <a class="gx-btn gx-btn-{{config ('app.entity_btns.'.strtolower($entity->type))}} col-md-3" href="{{route ('entities.show', [strtolower($entity->type), $entity->az, $entity->slug])}}">
                      {{title_case($entity->name)}}
                      <small class="mb-0 badge badge-light badge-ext float-right">{{$entity->refs_total}}</small>
                    </a>
                @endforeach
              @else
                <div class="col-md-12">
                  @include ('layouts.themes.mouldify.partials.empty', ['text' => 'No entities found'])
                </div>
              @endif

              @if ( !request()->has('q') )
              <div class="row mt-3">
                <div class="col-md-6 m-auto">
                  {!! $entities->links () !!}
                </div>
              </div>
              @endif
              @include ('layouts.themes.mouldify.partials.entity_disclaimer')

            </div>

          </div> <!-- end gx card -->
    </div> <!-- end col -->
  </div>

@stop

resources/views/entities/show.blade.php
@extends ('layouts.themes.mouldify.master')

@section ('sharing')
  @include ('layouts.themes.mouldify.partials.sharing', [
    'title' => title_case ($entity->name) . (isset($type) ? ' ('.entity_label($type).')' :'').' - Named Biblical Entities | RocketBible.com',
    'info'  => '',
  ])
@stop

@section ('content')
  <div class="page-heading">
      <h1 class="title">
        Named Entities
          <span class="font-weight-light"> / {{entity_label($type)}} / <span class="text-secondary">{{title_case($entity->name)}}</span> </span>
          <span class="mr-2 badge badge-secondary float-right">{{$entity->refs_total}}</span>
      </h1>
  </div>

  <div class="row mb-3">
    <div style="max-height: 250px;" id="book-group-100" class="ct-perfect-fourth bible-graph entity-group-graph" data-labels='{!! json_encode($BOOKS->sortBy('order')->pluck('abbrev')->all()) !!}' data-values="{!! json_encode ([chapter_values_map($BOOKS->count(), $bible->all())]) !!}"></div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="gx-card">
        @if ( isset($chapters) && count ($chapters) )
          @foreach ($chapters->groupBy('book_num') AS $book_num => $book_group)
            <h3 class="font-weight-semibold clearfix mt-3">
              <a href="{{route ('entities.book', [$type, $az, $entity->slug, $book_group->first()->book_slug])}}">
                {{$book_group->first()->book_title}}
              </a>
              <small class="mr-2 badge badge-secondary ml-2">{{$book_group->unique('chap_num')->sum('mentions')}}</small>
            </h3>

            <p class="text-muted">{{$BOOKS->where('order', $book_num)->first()->summary}}</p>

            <div class="row mb-3">
              <div style="max-height: 150px;" id="book-group-{{$book_num}}" class="ct-perfect-fourth entity-group-graph" data-labels="{{json_encode(range(1, $BOOKS->where('order', $book_num)->first()->chaps))}}" data-values="{!! json_encode ([chapter_values_map($BOOKS->where('order', $book_num)->first()->chaps, $book_group->sortBy ('chap_num')->pluck('mentions', 'chap_num')->all())]) !!}"></div>
            </div>

            <div class="row mt-0 mb-3">
              <div class="col-md-6 pl-2">
                @if (count ($book_group) )
                  <table class="table table-sm col-md-6 col-md-offset-3 ml-3">
                    <thead>
                      <tr>
                        <th class="text-center">Chapter</th>
                        <th class="text-center">Mentions </th>
                        <th class="text-center">Verses </th>
                      </tr>
                    </thead>
                    <tbody>
                    @foreach ($book_group->sortBy ('chap_num')->unique('chap_num') AS $chap_entity)
                    <tr>
                      <td class="text-center">
                        <a class="ml-2 mb-0 badge badge-warning" href="{{route ('entities.chapter', [$type, $az, $entity->slug, $chap_entity->book_slug, $chap_entity->chap_num])}}">{{$chap_entity->chap_num}}</a>
                      </td>
                      <td class="text-center">
                        <span class="badge badge-light">{{$chap_entity->mentions}}</span>
                      </td>
                      <td class="">
                        @if ( isset($chap_entity->verse_nums) )
                          <small>{{$chap_entity->verse_numbers_list ?? '_none_'}}</small>
                        @endif
                      </td>
                    </tr>
                    @endforeach
                    </tbody>
                  </table>
                @else
                  @include ('layouts.themes.mouldify.partials.empty', ['text' => 'No results found.'])
                @endif
              </div>
              <div class="col-md-6 pt-3">

                <div class="row">
                  <canvas id="chapter-radar-{{$book_num}}" class="chapter-radar-graph mt-3 m-auto" data-labels="{{json_encode(range(1, $BOOKS->where('order', $book_num)->first()->chaps))}}" data-values="{!! json_encode (chapter_values_map($BOOKS->where('order', $book_num)->first()->chaps, $book_group->sortBy ('chap_num')->pluck('mentions', 'chap_num')->all())) !!}"></canvas>
                </div>

              </div>
            </div>
            <hr style="margin-bottom: 30px;" />
          @endforeach

          <div class="row mt-0 mb-3">
            <div class="col-md-3 col-md-offset-2 m-auto">
              {!! $chapters->links() !!}
            </div>
          </div>

          @include ('layouts.themes.mouldify.partials.entity_disclaimer')


        @else
          @include ('layouts.themes.mouldify.partials.empty', ['text' => 'No results found in any book.'])
        @endif

    </div>
  </div>
</div>


@stop

@push ('js')
  <script>
  window.book_graphs = [];

  $( document ).ready(function() {
    $( ".entity-group-graph" ).each(function( index ) {
      window.book_graphs[index] = new Chartist.Line('#'+$(this).attr('id'), {
        labels: JSON.parse($(this).attr('data-labels')),
          series: JSON.parse($(this).attr('data-values'))
      }, {
          fullWidth: true,
          axisY: {
            onlyInteger: true
          },
          showArea: true
      });
    });

    $( ".chapter-radar-graph" ).each(function( index ) {

        var ctx = document.getElementById($(this).attr('id')).getContext("2d");
        var radarChart = new Chart(ctx, {
            type: 'radar',
            data: {
                labels: JSON.parse($(this).attr('data-labels')),
                datasets: [
                    {
                        label: "Chapter Spread",
                        backgroundColor: "rgba(200,0,0,0.6)",
                        fillColor: "#ADF7C9",
                        strokeColor: "#93E399",
                        pointColor: "#93E399",
                        pointStrokeColor: "#fff",
                        pointHighlightFill: "#fff",
                        pointHighlightStroke: "rgba(220,220,220,1)",
                        data: JSON.parse($(this).attr('data-values'))
                    }
                ]
            },
            options: {
                legend: {
                  display: false,
                },
                scaleShowLine: true,
                angleShowLineOut: true,
                scaleShowLabels: false,
                scaleBeginAtZero: true,
                angleLineColor: "rgba(0,0,0,.1)",
                angleLineWidth: 1,
                pointLabelFontFamily: "'Arial'",
                pointLabelFontStyle: "normal",
                pointLabelFontSize: 10,
                pointLabelFontColor: "#666",
                pointDot: true,
                pointDotRadius: 3,
                pointDotStrokeWidth: 1,
                pointHitDetectionRadius: 20,
                datasetStroke: true,
                datasetStrokeWidth: 2,
                datasetFill: true,
                responsive: true,
            }
        });
    });

    $( ".chapter-gauge-graph" ).each(function( index ) {
          var gaugeChart = new Chartist.Pie('#'+$(this).attr('id'), {
          series: JSON.parse($(this).attr('data-values'))
      }, {
          donut: true,
          donutWidth: 60,
          startAngle: 270,
          total: parseInt($(this).attr('data-total')),
          showLabel: false
      });
    });




  });

  </script>
@endpush